config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'
  get 'cars/new'
  post 'cars/create'
  get 'cars/show'
  devise_for :users
  resources :users
  resources :cars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "cars#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user 
  validates :brand, presence: true
  validates :model, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true
  has_many :cars

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @car = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = current_user.cars.new(car_params)
    if @car.save
      flash[:notice] = 'se salvo un auto correctamente'
      redirect_to car_path(@car)
    else
      flash[:error] = @car.errors.full_messages
      render :new
    end
  end

  def show
    @car = Car.find(params[:id])
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :price)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/index.html.erb
<h1>Autos disponibles para comprar</h1>
<form>
<label> Marca </label>
</br>
</br>
<label> Modelo </label>
</br>
</br>
<label> Precio </label>
</br>
</br>
</form>
<%= link_to "New Car", new_car_path %>

app/views/cars/new.html.erb
<h1>Subir un nuevo auto para su venta</h1>

<%= flash[:error]%>

<%= form_with model: @car, url: cars_path do |form| %>
    <label> Marca </label>
  <%= form.text_field :brand  %> 
  <br/>
  <label> Modelo </label>
  <%= form.text_field :model %>
  <br/>
  <label> Precio </label>
  <%= form.number_field :price %>
  <br/>
  <%= form.submit 'Enviar' %>
<% end %>

app/views/cars/show.html.erb
<h1>Detalles de auto ingresado</h1>
<strong>Marca: <%= @car.brand%></strong>
</br>
<strong>Modelo: <%= @car.model%></strong>
</br>
<strong>Precio: <%= @car.price%></strong>
</br>

<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarSalesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>